name: CoderCo Combined

on: [push]

jobs:
  builds:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        working-directory: chapter4

      - name: run tests
        run: python -m unittest discover
        working-directory: chapter4

      - name: notify us of success
        if: success()
        run: echo "Tests passed on ${{ matrix.python-version }}"

